### ISSUE TITLE
have you considered contributing to geetools ? 

### ISSUE THREAD

**Issue by 12rambau** [elbeejay/py_gee_tools#2]
@elbeejay I saw your lib while browsing pypi and I see that there is many overlapping with the geetools lib from the gee-community: https://github.com/gee-community

I'm in the process of refactoring and once v1 will be flying I will be more than happy to integrate missing functionalities. Let me know if you are interested.

**Comment by elbeejay** [comment]
Thanks for the note @12rambau. I'm actually no longer actively supporting, developing, or even using this package. I agree that the broader GEE community is doing some great work and I'd definitely look there in the future.

Going to archive the repository so it's clear there isn't ongoing development here
